[run]
    concurrency = 4
    tests = false

[linters-settings]
    [linters-settings.gocognit]
        min-complexity = 20

    [linters-settings.gofumpt]
        lang-version = "1.17"
        extra-rules = true

    [linters-settings.goconst]
        min-len = 2
        min-occurrences = 2

    [linters-settings.misspell]
        locale = "US"

[linters]
    disable-all = true
    enable = [
        "staticcheck",
        "gosimple",
        "ineffassign",
        "typecheck",
        "govet",
        "errcheck",
        "unused",
        "structcheck",
        "varcheck",
        "deadcode",

        "stylecheck",
        "gosec",
        "unconvert",
        "goconst",
        "gocognit",
        "depguard",
        "misspell",
        "unparam",
        "prealloc",
        "gofumpt",
        "exportloopref",
        "gocritic",
    ]
