# Golang CircleCI 2.0 configuration file 
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/golang:latest

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      - BINARY_NAME: "TySug-linux-amd64"
      - TEST_RESULTS: "/tmp/test-results"

    steps:
      - checkout
      - run: go version
      - run: mkdir -p ${TEST_RESULTS}
      - run: go get -u github.com/jstemmer/go-junit-report
      - run: go mod download all

      - run:
          name: Build
          command: |
            TAG=${CIRCLE_TAG:-dev}
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o "${TEST_RESULTS}/${BINARY_NAME}" -a -ldflags="-w -s -X main.Version=${TAG}" ./cmd/web

      - run:
          # Check if we have updates to minor/patch level packages we're explicitly referencing
          name: Dep check
          command: |
            go list -u -f '{{if (and (not (or .Main .Indirect)) .Update)}}{{.Path}}: {{.Version}} -> {{.Update.Version}}{{end}}' -m all 2> /dev/null

      - run:
          name: Lint
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0
            golangci-lint run

      - run:
          name: Test
          command: |
            go test -test.v ./... | go-junit-report > ${TEST_RESULTS}/report.xml
            go test -test.cover ./...
            go test -test.race ./...
            go test -test.benchmem -test.run=^$ -bench=. ./...

      - run:
          name: Codecov upload
          command: |
            bash <(curl -s https://codecov.io/bash)

  publish-image:
    docker:
      - image: circleci/golang:latest

    #working_directory: /home/circleci/TySug
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run:
          name: Building docker image
          command: |
            TAG=${CIRCLE_TAG:-devel}
            docker build -t dynom/tysug:${TAG} \
                --build-arg VERSION=${TAG} \
                --build-arg GIT_REF=${CIRCLE_SHA1} \
                . &&
            docker tag dynom/tysug:${TAG} dynom/tysug:latest
      - run: #docker login # @todo, figure out how to login, without exposing my creds -_-'
      - run: docker push dynom/tysug

workflows:
  version: 2
  build-test-push:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/
      - publish-image:
          requires:
            - build-and-test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/